"""
Django settings for trashnetwork_web project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y4ufrj0s#t46ichmt_i98%%!*4drvc__6pu+gz&30ve15@#c9g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEFAULT_CHARSET = 'utf-8'
ALLOWED_HOSTS = ['*']


# Application definition

APP_NAME = 'trashnetwork'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    APP_NAME,
    'rest_framework',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'trashnetwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trashnetwork.wsgi.application'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'trashnetwork.view.exception_handler.custom_exception_handler'
}

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'TrashNetwork',
        'USER': 'TrashNetwork',
        'PASSWORD': '4f5100635dc64621aa4ae256daae80046833ce8f',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

#Cache
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'TIMEOUT': None,
        'OPTIONS': {
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 15,
            },
            'MAX_ENTRIES': 1000
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# MQTT Broker
TN_MQTT_BROKER = {
    'HOST': 'localhost',
    'PORT': 23883,
    'CLIENT_ID': 'trashnetwork_webserver_user:admin',
    'USERNAME': 'trashnetwork_webserver_user:admin',
    'PASSWORD': '123456'
}

# MQTT Topic
MQTT_TOPIC_CLEANING_REMINDER = 'cleaning_reminder'
MQTT_TOPIC_LATEST_WORK_RECORD = 'latest_work_record'


# Scheduler
TN_SCHEDULER = {
    'REDIS_DB': 4,
    'THREAD_POOL_SIZE': 20,
    'MAX_JOB_INSTANCE': 5
}

TN_CLEANING_REMINDER = {
    'INTERVAL_MINUTES': 120,
    'TIME_RANGE_START_HOUR': 8,
    'TIME_RANGE_END_HOUR': 18,
    'TIME_RANGE_START_WEEKDAY': 1,
    'TIME_RANGE_END_WEEKDAY': 5
}

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# I18N
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "trashnetwork/locale")
]
